### ISSUE TITLE
Implement multiline string literal syntax

### ISSUE THREAD

**Issue by JarvisCraft** [CertainLach/jsonnet-rs#1]
# Description
Currently multiline string literal (`|||`) syntax is unsupported by parser and should be implemented to guarantee full spec-compatibility.

# Details
`Expr::Str` should be created for `|||` string literals.
Alternatively, a specific `Expr` may be added like `MultilineStr(Vec<String>)`.

# Example
... of a valid expression using `|||` syntax:
```jsonnet
{
  'foo': |||
    bar
    baz
    qux
  |||
}
```

**Comment by CertainLach** [comment]
Fixed in b7f33d336d240403484caa221e65bd250b0d91fa
